apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
  labels:
    app: nodeserver
spec:
  selector:
    matchLabels:
      app: nodeserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "nodeserver"
    spec:
      containers:
      - name: nodeserver
        image: "mhayk/hello-nodejs:v4"
        ports:
        - containerPort: 80
        env:
          - name: NAME
            value: "Mhayk"
          - name: AGE
            value: "35"