apiVersion: v1
kind: Pod
metadata:
 name: "nodeserver"
 labels:
  app: "nodeserver"
spec:
 containers:
  - name: nodeserver
    image: "mhayk/hello-nodejs:v4"
    ports:
    - containerPort: 80
    env:
      - name: NAME
        value: "Mhayk"
      - name: AGE
        value: "35"